config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles

  # Users
  resources :users, except: [ :new ]
  get "signup", to: "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: {minimum: 3, maximum: 20}
    validates :description, presence: true, length: {minimum: 6, maximum: 100}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    before_save :email_to_downcase
    validates :username, presence: true, 
        uniqueness: { case_sensitive: false }, 
        length: { minimum: 3, maximum: 25 }
        VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
        uniqueness: { case_sensitive: false }, 
        length: { maximum: 205 },
        format: { with: VALID_EMAIL_REGEX }
        

    def get_user_articles
        return self.articles
    end

    private
    
    def email_to_downcase
        self.email = email.downcase
    end

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :find_article, except: [:new, :index]
    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def show
    end

    def new
        @article = Article.new
    end
    
    def create

        @article = Article.new(article_params)
        @article.user = User.first
        if @article.save
            flash[:notice] = "the article was created successfully"
            redirect_to articles_path
        else
            render "new", status: :unprocessable_entity
        end
    end

    def edit
    end
    
    def update

        if @article.update(article_params)
            flash[:notice] = "the article was updated successfully"
            redirect_to articles_path
        else
            render "edit", status: :unprocessable_entity
        end
    end

    def destroy

        if @article.destroy
            flash[:notice] = "the article was deleted successfully"
            redirect_to articles_path
        else
            flash[:alert] = "was not deleted"
        end
    end

    private

    def find_article
        @article = Article.find_by_id(params[:id])
    end
    def article_params
        params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, except: [:new, :create, :index]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save 
            flash[:notice] = "Hi #{@user.username},you've successfully signed up"
            redirect_to articles_path
        else
            render "new", status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:notice] = "Account Information of #{@user.username} was successfully updated"
            redirect_to articles_path
        else
            render "edit"
        end
    end

    def index
        @users = User.all
    end

    def show
        @user_articles = @user.get_user_articles.paginate(page: params[:page], per_page: 5)
    end

    private

    def set_user
        @user = User.find(params[:id])
    end
    
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user)
        email_address = user.email
        hash = Digest::SHA256.hexdigest(email_address)
        size = 200
        params = URI.encode_www_form('s' => size)
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?#{params}"
        image_tag(gravatar_url, alt: user.username, class: "rounded mx-auto d-block")
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= stylesheet_link_tag 'form', media: 'all' %>
<div class="container" >
    <%= render 'shared/errors', obj: @article %>
    <div class="row justify-content-center">
        <div class="col-10">
            <%= form_with model: @article, class: "shadow p-3 mb-5 rounded form-form"  do |f| %>
                <div class="form-group row mt-4">
                    <%= f.label :title, class: "col-2 col-form-label text-dark"%> <br/>
                    <div class="col-10"><%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of Article"%></div>
                </div>

                <br>
                <div class="form-group row">
                    <%= f.label :description, class: "col-2 col-form-label text-dark"%> <br/>
                    <div class="col-10"><%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of Article"%></div>
                </div>
                <br>
                <div class="form-group row justify-content-center">
                    <%= f.submit class: "submit-btn" %>
                </div>
            <% end %>
        </div>
    </div>
</div>
<h5 class="d-flex justify-content-center">
    <%= link_to "[ Cancel and return to articles listing ]", articles_path, class: "text-info text-lg" %>
</h5>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit the article with id <%= @article.id%></h1>
<%= render "form" %>

app/views/articles/index.html.erb
<%= stylesheet_link_tag 'index', media: 'all' %>
<h1 class="text-center mt-4">All articles</h1>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<div class="container">
    <% @articles.each do |a| %>
        <div class="row  d-flex justify-content-center ">
            <div class="col-8 mt-4 ">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header">
                    By <%= a.user.username %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to a.title, article_path(a), class: "text-dark" %></h5>
                        <p class="card-text"><%= truncate(a.description, length: 50) %></p>
                    </div>
                    <div class="container mb-4 d-flex justify-content-center">
                        <ul class="nav nav-tabs card-header-tabs">
                        <li class="nav-item">
                            <%= link_to "View", article_path(a), class: "btn btn-outline-primary mx-1"%>               
                        </li>
                        <li class="nav-item">
                            <%= link_to "Edit", edit_article_path(a), class: "btn btn-outline-info  mx-1"%>                
                        </li>
                        <li class="nav-item">
                        <%= button_to "Delete", article_path(a), class: "btn btn-outline-danger  mx-1", method: :delete, onclick: "return confirm('Are you sure?')" %> 
                        </li>
                        </ul>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(a.created_at)%> ago</small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>
<% unless @articles.length < 4%>
    <div class="flickr_pagination " style="margin-bottom: 100px">
        <%= will_paginate @articles, :container => false %>
    </div>
<% end %>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create new Article</h1>   
<%= render "form" %>

app/views/articles/show.html.erb
<div class="row  d-flex justify-content-center ">
<div class="col-8 mt-4 ">
    <h3 class="card-title text-center mb-4"><%= @article.title %></h3>
    <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header">
            By <%= @article.user.username %>
        </div>
        <div class="card-body">
            <p class="card-text"><%= simple_format(@article.description) %></p>
        </div>
        <div class="container mb-4 d-flex justify-content-center">
            <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info  mx-1"%>                
            </li>
            <li class="nav-item">
            <%= button_to "Delete", article_path(@article), class: "btn btn-outline-danger  mx-1", method: :delete, onclick: "return confirm('Are you sure?')" %> 
            </li>
            </ul>
        </div>
        <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at)%> ago</small>
        </div>
    </div>
</div>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" aria-label="Close" onclick="this.parentElement.style.display='none'"></button>
    </div>
  <% end %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Heureka</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= render partial: "shared/navbar"%>
    <%= render partial: "layouts/messages"%>

    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/4f4ee9b10f.js" crossorigin="anonymous"></script>
    <%= render partial: "shared/footer"%>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<%= link_to "home", root_path %>

app/views/pages/home.html.erb
<%= stylesheet_link_tag 'home', media: 'all' %>
<div class="container">
    <div class="bg-medium p-5 rounded-lg m-3">
        <h1 class="display-4">Heureka...</h1>
        <p class="lead"></p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-about btn-lg" href="#" role="button">Learn more</a>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
        <ul>
        <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
        <button type="button" class="btn-close" aria-label="Close" onclick="this.parentElement.style.display='none';"></button>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<%= stylesheet_link_tag 'home', media: 'all' %>
<footer class="footer">
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.9); color: white">
        © 2024 Education in 
        <a style="color: white" href="https://bic.com.de/">B.I.C.</a>
    </div>
</footer>
  

app/views/shared/_navbar.html.erb
<%= stylesheet_link_tag 'home', media: 'all' %>
<%= javascript_include_tag 'navbar' %>

<nav class="navbar-black navbar navbar-expand-lg bg-body-tertiary" style="height: 50px">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><%= image_tag 'app-logo-light-blue.png', alt: 'Logo App', class: 'app-logo' %></a>
    <button class="white-font navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/users">Bloggers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/articles">All Articles</a>
        </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navDrowpdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Articles
        </a>
        <ul class="dropdown-menu" id="dropdownMenu" style="display: none" >
          <li><a class="dropdown-item" href="/articles/new">NEW</a></li>
          <li><a class="dropdown-item" href="/articles">All articles</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="#">Contact</a></li>
        </ul>
      </li>
      </ul>
      <a href="/signup">
        <button class="login-btn btn" style="height: 36px">Sign up</button>
      </a>
    </div>
  </div>
</nav>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    let isDropdownOpen = false;
    document.addEventListener("click", function(event) {
      const dropdown = document.getElementById("navDrowpdown");
      if (event.target === dropdown) {
          toggleDropdown();
      } else {
      }
    });
    function toggleDropdown() {
      isDropdownOpen = !isDropdownOpen;
      const dropdownMenu = document.getElementById("dropdownMenu");
      if (isDropdownOpen) {
          dropdownMenu.style.display = "block";
      } else {
          dropdownMenu.style.display = "none";
      }
    }
  });
</script>

app/views/users/_form.html.erb
<%= stylesheet_link_tag 'form', media: 'all' %>
<div class="container" >
    <%= render 'shared/errors', obj: @user %>
    <div class="row justify-content-center">
        <div class="col-10">
            <%= form_with model: @user, class: "shadow p-3 mb-5 rounded form-form"  do |f| %>
                <div class="form-group row mt-4">
                    <%= f.label :username, class: "col-2 col-form-label text-dark"%> <br/>
                    <div class="col-10"><%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username"%></div>
                </div>

                <br>
                <div class="form-group row">
                    <%= f.label :email, class: "col-2 col-form-label text-dark"%> <br/>
                    <div class="col-10"><%= f.email_field :email, rows: 10, class: "form-control shadow rounded", placeholder: "Enter a valid email"%></div>
                </div>
                <br>
                <div class="form-group row">
                    <%= f.label :password, class: "col-2 col-form-label text-dark"%> <br/>
                    <div class="col-10"><%= f.password_field :password, rows: 10, class: "form-control shadow rounded", placeholder: "Choose a password"%></div>
                </div>
                <br>
                <div class="form-group row justify-content-center">
                    <%= f.submit class: "submit-btn" %>
                </div>
            <% end %>
        </div>
    </div>
</div>
<h5 class="d-flex justify-content-center">
    <%= link_to "[ Cancel and return to users listing ]", users_path, class: "text-info text-lg" %>
</h5>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit user with id <%= @user.id %></h1>
<%= render "form" %>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'index', media: 'all' %>
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="container">
    <% @users.each do |u| %>
        <div class="row  d-flex justify-content-center ">
            <div class="col-8 mt-4 ">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header">
                        <%= u.username %> 
                    </div>
                    <div class="card-body">
                        <p class="card-text"><%= truncate(u.email, length: 50) %></p>
                        <%= gravatar_for u %>
                        <%= pluralize(u.articles.count, "article")%> 
                    </div>
                    <div class="container mb-4 d-flex justify-content-center">
                        <ul class="nav nav-tabs card-header-tabs">
                        <li class="nav-item">
                            <%= link_to "View", user_path(u), class: "btn btn-outline-primary mx-1"%>               
                        </li>
                        <li class="nav-item">
                            <%= link_to "Edit", edit_user_path(u), class: "btn btn-outline-info  mx-1"%>                
                        </li>
                        <li class="nav-item">
                        <%= button_to "Delete", user_path(u), class: "btn btn-outline-danger  mx-1", method: :delete, onclick: "return confirm('Are you sure?')" %> 
                        </li>
                        </ul>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Joined <%= time_ago_in_words(u.created_at)%> ago</small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Heureka</h1>
<%= render "form" %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>
<%= gravatar_for @user %>

<%= stylesheet_link_tag 'index', media: 'all' %>
<h1 class="text-center mt-4"> Your articles</h1>
<div class="flickr_pagination">
    <%= will_paginate @user_articles, :container => false %>
</div>
<div class="container">
    <% @user_articles.each do |a| %>
        <div class="row  d-flex justify-content-center ">
            <div class="col-8 mt-4 ">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header">
                        <h5 class="card-title"><%= link_to a.title, article_path(a), class: "text-dark" %></h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text"><%= truncate(a.description, length: 50) %></p>
                    </div>
                    <div class="container mb-4 d-flex justify-content-center">
                        <ul class="nav nav-tabs card-header-tabs">
                        <li class="nav-item">
                            <%= link_to "View", article_path(a), class: "btn btn-outline-primary mx-1"%>               
                        </li>
                        <li class="nav-item">
                            <%= link_to "Edit", edit_article_path(a), class: "btn btn-outline-info  mx-1"%>                
                        </li>
                        <li class="nav-item">
                        <%= button_to "Delete", article_path(a), class: "btn btn-outline-danger  mx-1", method: :delete, onclick: "return confirm('Are you sure?')" %> 
                        </li>
                        </ul>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(a.created_at)%> ago</small>
                    </div>
                </div>
            </div>
        </div>
   
    <% end %>
</div>
<% unless @user_articles.length < 4%>
    <div class="flickr_pagination " style="margin-bottom: 100px">
        <%= will_paginate @user_articles, :container => false %>
    </div>
<% end %>